### ISSUE TITLE
Error reading raw blackbox file. CSV does not work eather 

### ISSUE THREAD

**Issue by krzysztofkuczek** [ElvinC/gyroflow#111]
Hi,
I'm trying to use directly BFL and got the error
`log C:/Users/kku/Downloads/blackbox-tools-0.4.3-windows/LOG00003.BFL has type 'Blackbox raw file'
Automatically detected gyro log file: LOG00003.BFL
Opening C:/Users/kku/Downloads/blackbox-tools-0.4.3-windows/LOG00003.BFL
Error reading raw blackbox file. Try converting to CSV in blackbox explorer
Log extraction failed`

Then i used black box tools to convert bfl to csv...
`Couldn't guess log type of C:/Users/kku/Downloads/blackbox-tools-0.4.3-windows/LOG00003.01.csv
Log extraction failed`

You can check both files if you want
https://drive.google.com/file/d/1EiDoMtzriwLHQ-gfbtoSuVw8opSoOb8w/view?usp=sharing
What should i do?
Thank you in advance
Kris

**Comment by ElvinC** [comment]
The detection works by looking for a header on the first line, which doesn't seem to be present in your file. If you manually select the blackbox csv format, it works

**Comment by krzysztofkuczek** [comment]
Thank you
