### ISSUE TITLE
Which Gyro Log Type for Sony a7s III?

### ISSUE THREAD

**Issue by throttlenerd** [ElvinC/gyroflow#115]
I think I tried every one, except for ones titled "GoPro" and "Insta 360" and it doesn't seem to recognize the log data inside the .mp4 file, however it is there, according to Catalyst Browse.

Thanks!

**Comment by ElvinC** [comment]
You can convert it to the blackbox format with telemetry_parser and load that: https://github.com/AdrianEddy/telemetry-parser
alternatively telemetry_parser is used as a module in the dev branch and can be selected as one of the log parser types.
