### ISSUE TITLE
Lossless stabilisation

### ISSUE THREAD

**Issue by babipsylon** [ElvinC/gyroflow#119]
For some high end cameras, like the zcam E2, will it be possible in the future to do lossless stabilization in zraw or prores formats? With more than 8bit depth output files? I heard about a da vinci resolve plugin, but couldn't find much if and where it's available at this time (dec 2021).

Cheers

Ruben

**Comment by ElvinC** [comment]
For now you can try this: https://github.com/ilya-epifanov/gyroflow-ofx

**Comment by babipsylon** [comment]
Thanks. Does it give higher output quality? Or not really?

**Comment by ElvinC** [comment]
It can, but I've heard that that plugin can be a bit slow with rendering

**Comment by babipsylon** [comment]
Thanks, will have a look at it!
