### ISSUE TITLE
Idea: mux gyro data into insta360 movie

### ISSUE THREAD

**Issue by knoopx** [ElvinC/gyroflow#12]
Have you used insta360 studio? It basically applies gyro correction realtime and allow you to tweak some stuff. Maybe we can be able to embed the gyro data into the video in the format insta360 studio expects and let it do the magic?

**Comment by ElvinC** [comment]
Hey. I haven't tried insta360 software before, but that sounds interesting. I'm guessing that similar problems to [BlackboxToGPMF](https://github.com/Cleric-K/BlackboxToGPMF/tree/gui) + RSGO may arise where the software only supports the "default" lens parameters, leading to results that warp around a bit if not accounted for. It might work for some lenses, but it's not an universal solution. A couple of people are working on doing it the other way around, that is, extracting gyro metadata from insta360 files for use with blackboxtogpmf/gyroflow (check out the Discord server linked in the main readme if you're interested).
