### ISSUE TITLE
Phone app logs error: unsupported file format

### ISSUE THREAD

**Issue by nikster89** [ElvinC/gyroflow#145]
I've tried to log via smartphone's apps - not sure if I found ones from the supported list (Sensor Logger, G-Field Recorder, Gyro) - so I tested G-Sensor logger and Sensor Logger on two different phones. I tried to open.csv files in Gyroflow, and received 'unsupported file format' error. My questions:
- is it any difference between the apps?
- is it possible to provide some instructions and/or supported apps links?
Thank you!

**Comment by ElvinC** [comment]
Hey, you're currently in the legacy repo. Have a look at the issues over here: https://github.com/gyroflow/gyroflow
