### ISSUE TITLE
Video lag after export

### ISSUE THREAD

**Issue by Oskar-prg** [ElvinC/gyroflow#152]
Hy, I'm using Gyroflow 1.2.0 and after the export in multiple point of the video I have a lag. What I'm doing wrong ?
This is the video: [link](https://1drv.ms/v/s!As5Cv5yCAzGvgvpNNBeJ2zbV5Fmj9A)
You can see the lag after the 00:03 min
The camera is a GoPro Hero 8
These are my settings:

![Settings](https://user-images.githubusercontent.com/62244979/187194051-9ccbadae-30a4-43ad-b9b4-73011038d6d9.jpg)

**Comment by ElvinC** [comment]
Hi, this is the legacy repo, please refer to the support discord where you can also share the input file for us to look at: https://gyroflow.xyz/discord/
Active repo: https://github.com/gyroflow/gyroflow

Looks like it might be an issue with the input file. Normally Hero 8 files work perfectly, so maybe make sure you're on the latest GoPro firmware.
