### ISSUE TITLE
Black Orbs Visible Throughout footage

### ISSUE THREAD

**Issue by E5TIE** [ElvinC/gyroflow#157]
Using a new Gopro Hero 11 mini. I'm getting weird black orbs throughout the footage. Check all settings to see if there's a mistake but it seems like the gyro data is not reading correctly. The same issue happen when using the slipt recording option.
![gyroflow](https://user-images.githubusercontent.com/131156251/232749213-276897c4-9123-4823-b655-131a6383eb2e.jpg)
![gyroflow2](https://user-images.githubusercontent.com/131156251/232749297-d24a72d6-303e-46db-960a-b1ac6f0055a7.jpg)

**Comment by E5TIE** [comment]
The IMU orientation seems to change after a flip. Does that mean that the orientation feature on the gopro has to be locked?

**Comment by ElvinC** [comment]
This is the inactive legacy version. Please go here: https://github.com/gyroflow/gyroflow
