### ISSUE TITLE
AttributeError: type object 'Rotation' has no attribute 'from_matrix'

### ISSUE THREAD

**Issue by hyperion11** [ElvinC/gyroflow#16]
Hi, can't run stabilization
OS linux ubuntu
Record test video on Runcam Hybrid 4k
Compute offset and make GPMF Emulated video file
![Screenshot from 2021-01-26 22-30-16](https://user-images.githubusercontent.com/13326299/105866010-17d83080-6026-11eb-9d2e-b9c414729e8f.png)
after this open exported video file in latest gyroflow with this settings. Not calibrate camera yet, but set similar camera settings

![Screenshot from 2021-01-26 22-32-39](https://user-images.githubusercontent.com/13326299/105866292-6d144200-6026-11eb-9939-a8e2a01eb31c.png)

at 30 seconds video shaking started
and this error i receive in console

Gyro rate: 396.2234948150441 Hz, should be close to 200 or 400 Hz
Starting sync. Smoothness: 0.85, sync1: 5.0 (frame 299), sync2: 30.0 (frame 1798), OF slices of 60 frames
Analyzing frame: 0/60
Traceback (most recent call last):
  File "gyroflow.py", line 1452, in recompute_stab
    self.stab.auto_sync_stab(smoothness,sync1_frame, sync2_frame, OF_slice_length)
  File "/home/hyperion/gyroflow-master/stabilizer.py", line 24, in auto_sync_stab
    d1, times1, transforms1 = self.optical_flow_comparison(sliceframe1, slicelength)
  File "/home/hyperion/gyroflow-master/stabilizer.py", line 222, in optical_flow_comparison
    thisrot = Rotation.from_matrix(rots[0]) # First one?
AttributeError: type object 'Rotation' has no attribute 'from_matrix'

**Comment by ElvinC** [comment]
Probably an outadted scipy package. Try running

    C:\Users\elvin>python
    >>> from scipy.spatial.transform import Rotation
    >>> Rotation.from_matrix
    <bound method Rotation.from_matrix of <class 'scipy.spatial.transform.rotation.Rotation'>>

If you get the same error try reinstalling/updating scipy. [See this](https://github.com/scipy/scipy/issues/11685).

**Comment by hyperion11** [comment]
thank you!
hyperion@UbuntuDev:~$ pip3 install scipy
Requirement already satisfied: scipy in /usr/lib/python3/dist-packages (1.3.3)

after upgrading receive another error
hyperion@UbuntuDev:~$ pip3 install --upgrade scipy
Collecting scipy
  Downloading scipy-1.6.0-cp38-cp38-manylinux1_x86_64.whl (27.2 MB)
     |████████████████████████████████| 27.2 MB 54 kB/s 
Requirement already satisfied, skipping upgrade: numpy>=1.16.5 in /usr/lib/python3/dist-packages (from scipy) (1.17.4)
Installing collected packages: scipy
Successfully installed scipy-1.6.0

now sync working, but i have another problem. This issue close
