### ISSUE TITLE
GoPro Imu-Camera Calibration

### ISSUE THREAD

**Issue by urbste** [ElvinC/gyroflow#17]
Hey I stumbled upon your repo searching for interesting GoPro footage stabilization.
I have not tested your code yet, however I saw that you are also experimenting with the calibration of IMU and camera.
I released my personal exploration repository for calibrating GoPros: https://github.com/urbste/OpenImuCameraCalibrator
Maybe you'll find something useful in there ;)
Cheers
Steffen

**Comment by ElvinC** [comment]
Wow that's amazing work. I'll make sure to have a look through it. Thanks for sharing it!
