### ISSUE TITLE
Pacman version 

### ISSUE THREAD

**Issue by cprpolo** [ElvinC/gyroflow#24]
Hi! 
very interesting project :)
I'd like to test it in Linux, running Manjaro (arch based) at the moment, so if you could port it would be great :)
or instructions to build it locally?

**Comment by ElvinC** [comment]
Not sure if you'll run into any quirks, but if you have python you should be able to clone the repo, install the dependencies using poetry and run as briefly described [here](https://elvinchen.com/gyroflow/guide/).
