### ISSUE TITLE
Phone cameras?

### ISSUE THREAD

**Issue by nicholaskross** [ElvinC/gyroflow#34]
Is there a way to create lens presets for smartphones? Like iPhones, Android phones, etc. Do they record gyroscope data with video? How would that kind of setup work?

**Comment by ElvinC** [comment]
They don't typically record gyro logs with the video. For android you can try the hyperlapse app which I believe does gyro-based stabilization. Other than that, the EIS in the phone app uses the gyroscope as well. For use with gyroflow you would need an app that records a gyro log (sufficiently high sample rate) at the same time as video.

**Comment by nicholaskross** [comment]
Okay, thanks!
