### ISSUE TITLE
Feature request: dynamic zoom and rotation

### ISSUE THREAD

**Issue by WizzX-FPV** [ElvinC/gyroflow#36]
I really like gyroflow, as I can use it on any camera but, 
right now there's only one point which is better on Reel steady - automatic zooming/un-zooming and rotation of video if there's some peaks in movement (where's now we can see some black areas in video).
Do you think this can be implemented? ideally with some kind of slider with 0-100% 
Also what about horizon lock (as flowstate stabilization on insta360?
thank you,

WizzX

**Comment by ElvinC** [comment]
These are things that are currently work in progress. There are some tests with horizon lock and other stuff that you can find on the rsgoblackbox discord server: https://discord.com/invite/Rs4GBPm
