### ISSUE TITLE
Feature request: Custom background color

### ISSUE THREAD

**Issue by Amzd** [ElvinC/gyroflow#38]
I know the black parts aren't really a background color but just empty space but it would be cool if we could fill it with a custom color. 

This would make it nicer to post on places where you control the background color like on your own website. 

Up until we get automatic zooming this will make it a little bit nicer to watch.

**Comment by truog2003** [comment]
Cool !...

Em sex., 2 de abr. de 2021 às 08:16, Amzd ***@***.***>
escreveu:

**Comment by ElvinC** [comment]
Good idea. Other than background color selection, there are also different ways the empty area can be filled in. Some alternatives are reflection and continue with last color:
![image](https://user-images.githubusercontent.com/20195216/113412917-c8153d00-93b9-11eb-9c38-39bcc9d2ee24.png)
![image](https://user-images.githubusercontent.com/20195216/113412847-9ac88f00-93b9-11eb-91f9-b45f441bdc68.png)

I'll make sure to add these options

**Comment by Amzd** [comment]
That reflection actually properly tricks my brain 🤯

**Comment by ElvinC** [comment]
Added in dev branch
