### ISSUE TITLE
Ignore training/leading whitespace in csv headers

### ISSUE THREAD

**Issue by maxbl4** [ElvinC/gyroflow#48]
INav blackbox converter adds whitespace to format CSV. I have to manually remove whitespace from headers in order for gyroflow to accept logs

**Comment by ElvinC** [comment]
Could you attach an INAV log I can take a look at?

**Comment by avsaase** [comment]
@ElvinC this is the same issue I reported in https://github.com/ElvinC/gyroflow/issues/22.

**Comment by ElvinC** [comment]
Ah I see, I've added a fix on my dev version

**Comment by OMGChase** [comment]
> Ah I see, I've added a fix on my dev version. Maybe someone can also mention it to the INav blackbox converter people, unless the whitespace is on purpose.

Hello. Brought it up here with iNav guys and has been fixed in a pull request. Can see here:
https://github.com/iNavFlight/blackbox-tools/issues/40
