### ISSUE TITLE
Add configurable limit to screen movement

### ISSUE THREAD

**Issue by maxbl4** [ElvinC/gyroflow#49]
Right now on sharp moves video may be moved too much, so black borders will be seen at any crop. Please add configurable limit for video movement

**Comment by ElvinC** [comment]
Something like this is currently being tried out, and marcroe has a branch with an alternative orientation filtering method: https://github.com/marcroe/gyroflow/tree/nonlinearfilter

Feel free to join the discord linked in the readme if you want to try it out and give feedback.

**Comment by maxbl4** [comment]
I've tried the latest dev version. Works great most of the time. I would only want to be able to set the limit on adaptive zoom. Right now in case of flip or roll it zooms in to 100500% :)

**Comment by ElvinC** [comment]
Basic rotation limit added to dev branch. More options on the way
