### ISSUE TITLE
Opencv-python version not compatible with python 3.9

### ISSUE THREAD

**Issue by zap-wizard** [ElvinC/gyroflow#61]
Hi

In the `pyproject.toml` file the required `opencv-python` version is set to 4.1.2 . However apparently there's no wheels of that version for python 3.9 [see here](https://pypi.org/project/opencv-python/4.1.2.30/#files) ... As poetry uses the latest possible python version 3.9 (`python = ">=3.7,<3.10"` in pyproject.toml) I had to change it to `python = ">=3.7,<3.9"` in order for `poetry install` to work.

So I guess either the python version or opencv version should be changed ? I didn't make a pr as I'm not sure what to do...

**Comment by ElvinC** [comment]
That has been changed in the dev branch: https://github.com/ElvinC/gyroflow/tree/dev
