### ISSUE TITLE
sync problem & QCoreApplication

### ISSUE THREAD

**Issue by minzukas** [ElvinC/gyroflow#79]
Hi, 

I am still struglling to get it to work. My stabilized videos look actually worse than originals. I gues it is due to offset differences, not sure why though as I use video and csv straight out of runcam 5 orange, lens model is 1440 what I shoot with.  Perhaps anyone could help me out. 
ALso I get different graphs than shon on the totorial, but perhaps it is intended.
Tried versions 0.2.1 & 0.2.2 - get same results
![graph](https://user-images.githubusercontent.com/42060128/130607176-2eab0924-1a92-47c3-adb7-2e91fa146f59.png)

![sync](https://user-images.githubusercontent.com/42060128/130606966-02139a8b-981f-4bb7-8362-4993b59290e6.png)

**Comment by ElvinC** [comment]
Did you try using auto sync in the current dev branch?

**Comment by minzukas** [comment]
I get same shaky video if timestamps left unchanged in current dev

**Comment by ElvinC** [comment]
Any luck since with the newer versions? Have a look here if not: https://docs.google.com/document/d/1mLrMd8itLYiGNdQh4oWqz-s3g16bfu-TkQNCS_ZqOnA/edit#

**Comment by minzukas** [comment]
All good with newer versions, only wish non-linear stretching was working. Thanks a lot for
