### ISSUE TITLE
Video only renders first second or so with GoPro Hero 8 2.7k 30 and 60 fps on MacOS

### ISSUE THREAD

**Issue by christopher-kapic** [ElvinC/gyroflow#93]
I'm not sure if this is related to MiniGod's [issue](https://github.com/ElvinC/gyroflow/issues/57)--everything seems to work fine, until I actually try to export the video. When I check the result, only the first second or so is rendered, and then I get a black screen with just audio for the remainder of the video.

**Comment by ElvinC** [comment]
Please add the relevant errors etc. that appear.

**Comment by christopher-kapic** [comment]
I got it to work, but I don't recall what I did. If it happens again I will submit a new issue. For now, I will close it. Sorry to bother you.

**Comment by ElvinC** [comment]
Could the the third question listed here: https://elvinchen.com/gyroflow/FAQ/

**Comment by christopher-kapic** [comment]
I think that's it.
