### ISSUE TITLE
Gyroflow export just one frame but full audio

### ISSUE THREAD

**Issue by ElMute** [ElvinC/gyroflow#98]
Hi, when I try to export my stabilize footage, rendering is really short, and I get only one frame on my MP4, with full length of the original clip, and full audio
What's wrong ?
Thanks for your help

**Comment by ElvinC** [comment]
Please post any errors you're getting. But chances are it's this:  https://elvinchen.com/gyroflow/FAQ/#im-getting-an-error-with-unable-to-read-multiple-frames-when-trying-to-render-a-video

**Comment by ElvinC** [comment]
Fixed in dev branch
